### ISSUE TITLE
If you have more time, what would you add or improve?

### ISSUE THREAD

**Issue by alex-nexus** [bcfalah/music-service-api#4]

**Comment by bcfalah** [comment]
I would add these things, in order of priority:

- Authorization
- Pagination
- Add filters and ordering to index actions (probably with [Ransack gem](https://github.com/activerecord-hackery/ransack))
- Performance issues (treated in another issue)
- Internationalization (using i18n, specially for error messages)
- Rate Limiting (limiting the number of requests for a given time interval, for improving security and being prepared for users using our API in the wrong way)
- Use S3 for storing images instead of using a simple string field for storing urls (it will depend on the requirements)

**Comment by alex-nexus** [comment]
nice, thanks for the answers
