### ISSUE TITLE
random questions

### ISSUE THREAD

**Issue by alex-nexus** [bcfalah/music-service-api#5]
1. Any particular reason for choosing `gem 'swagger-docs'`?
2. Any particular reason for choosing `ActiveModel::Serializer`?
3. Did you actually get the circle ci running?

**Comment by bcfalah** [comment]
1. The main reason is that I remembered I had used it before with success on another project.
It was easy to me to add documentation for each endpoint, and at the same time you add the documentation, you are also building a view for being able to interact with the endpoint (using swagger-ui gem). I know I could have achieved the same with _grape_ and _grape-swagger_, but I had swagger-docs in mind and decided to use it as it seemed to be a very good tool too.

1. Pretty the same than with swagger-docs, I had used it before with success on a recent project.
I remember that in that project we were using jbuilder for rendereing the json views, and then decided to migrate to _ActiveModel::Serializer_ because it was faster, less verbose and easier to declare and use (by declaring a ruby class, similar to ActiveRecord in that you can define associations in the serializer).
It also allows you to choose what type of JSON structure you will use by default and to have and use different serializers for the same model.

1. Yes, it is running and connected with github and heroku, the idea was to deploy automatically (when pushing to master) only if all specs passed.

**Comment by alex-nexus** [comment]
great, thanks!
